[package]
name = "example"
version = "0.1.0"
edition = "2024"

[dependencies]
remotro = { path = "../lib" }
tokio = { version = "1", features = ["full"] }
log = "0.4"
env_logger = "0.11"
serde_json = "1.0.140"
